import {
  MemoryNode,
  ActiveMemory,
  Schema,
  Message,
  Turn,
  LineageEntry,
} from './types';

export const BUDGET_TOTAL = 2048;

const POS = {
  wardV1: { x: 32, y: 27 },
  wardV2: { x: 51, y: 27 },
  pytestV3: { x: 70, y: 27 },
  pytestNote: { x: 32, y: 43 },
  fastapi: { x: 32, y: 58 },
  paymentsApi: { x: 55, y: 58 },
  ecs: { x: 32, y: 78 },
  deployV2: { x: 70, y: 78 },
};

const TESTING_LINEAGE: LineageEntry[] = [
  {
    id: 'lineage-ward-v1',
    status: 'SUPERSEDED',
    contentSnippet: 'Ward for the payments suite.',
    timestamp: 'Jun 02 · 09:14',
    trigger: 'Initial testing preference captured from the payments setup session.',
  },
  {
    id: 'lineage-ward-v2',
    status: 'SUPERSEDED',
    contentSnippet: 'Ward for every backend test with shared fixtures.',
    timestamp: 'Jun 11 · 16:42',
    trigger: 'Expanded after the user standardized newer backend work on Ward.',
  },
  {
    id: 'lineage-pytest-v3',
    status: 'ACTIVE',
    contentSnippet: 'pytest with fixtures; Ward retired across the codebase.',
    timestamp: 'Jul 19 · 11:08',
    trigger:
      'Contradiction event: user explicitly replaced Ward with pytest as the current testing standard.',
  },
];

export const initialMessages: Message[] = [
  {
    id: 'sys-1',
    role: 'system',
    content: 'Session 3 ended · Maintenance running',
    metadata: 'IAAF: 2 memories archived\nASC: 1 schema updated',
  },
  { id: 'sys-2', role: 'system', content: 'Session 4' },
  {
    id: 'msg-1',
    role: 'user',
    content: 'Help me set up tests for the payments module',
  },
  {
    id: 'msg-2',
    role: 'agent',
    content:
      "Here's your Ward test suite for payments — aligned with the broader Ward + fixtures pattern you were using before the later pytest migration.",
  },
];

export const initialNodes: MemoryNode[] = [
  {
    id: 'node-ward-v1',
    label: 'Ward v1',
    status: 'SUPERSEDED',
    stability: 0.45,
    ...POS.wardV1,
    lineage: TESTING_LINEAGE,
  },
  {
    id: 'node-ward-v2',
    label: 'Ward v2',
    status: 'ACTIVE',
    stability: 0.62,
    ...POS.wardV2,
    parentId: 'node-ward-v1',
    lineage: TESTING_LINEAGE,
  },
  {
    id: 'node-fastapi',
    label: 'FastAPI',
    status: 'ACTIVE',
    stability: 0.78,
    ...POS.fastapi,
  },
  {
    id: 'node-pytest-note',
    label: 'pytest note',
    status: 'ACTIVE',
    stability: 0.22,
    ...POS.pytestNote,
  },
  {
    id: 'node-ecs',
    label: 'ECS + Docker',
    status: 'ACTIVE',
    stability: 0.8,
    ...POS.ecs,
  },
];

export const initialActiveMemories: ActiveMemory[] = [
  { id: 'am-ward', label: 'Ward preference v2', utility: 0.91 },
  { id: 'am-ecs', label: 'ECS deployment', utility: 0.87 },
  { id: 'am-fastapi', label: 'FastAPI structure', utility: 0.73 },
  {
    id: 'am-pytest-old',
    label: 'Older pytest note',
    utility: 0.21,
    excluded: true,
  },
];

export const initialSchemas: Schema[] = [
  {
    id: 'sch-testing',
    type: 'PREFERENCE',
    summary: 'Testing → Ward v2',
    confidence: 0.85,
  },
  {
    id: 'sch-deploy',
    type: 'PROCEDURE',
    summary: 'Deploy → ECS',
    confidence: 0.92,
  },
  { id: 'sch-db', type: 'FACT', summary: 'DB → DynamoDB', confidence: 0.78 },
];

export const INITIAL_BUDGET = 1847;
export const INITIAL_SESSION_LABEL = 'Session 4';

export const turns: Turn[] = [
  {
    id: 'turn-1',
    chip: 'Add a Stripe webhook route to the API',
    userMessage: 'Add a webhook route to the API for processing Stripe payments.',
    agentMessage:
      'Scaffolded the webhook route on your FastAPI app. That reinforced the FastAPI memory, and I stored a new Payments API memory for it.',
    sessionLabel: 'Session 4',
    preSnapshotDelay: 1300,
    replyDelay: 2400,
    dwellAfter: 2800,
    nodes: [
      {
        id: 'node-ward-v1',
        label: 'Ward v1',
        status: 'SUPERSEDED',
        stability: 0.45,
        ...POS.wardV1,
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-ward-v2',
        label: 'Ward v2',
        status: 'ACTIVE',
        stability: 0.62,
        ...POS.wardV2,
        parentId: 'node-ward-v1',
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-fastapi',
        label: 'FastAPI',
        status: 'ACTIVE',
        stability: 0.95,
        ...POS.fastapi,
      },
      {
        id: 'node-pytest-note',
        label: 'pytest note',
        status: 'ACTIVE',
        stability: 0.2,
        ...POS.pytestNote,
      },
      {
        id: 'node-ecs',
        label: 'ECS + Docker',
        status: 'ACTIVE',
        stability: 0.8,
        ...POS.ecs,
      },
      {
        id: 'node-payments-api',
        label: 'Payments API',
        status: 'ACTIVE',
        stability: 0.45,
        ...POS.paymentsApi,
        parentId: 'node-fastapi',
        isNew: true,
      },
    ],
    activeMemories: [
      { id: 'am-fastapi', label: 'FastAPI structure', utility: 0.96 },
      { id: 'am-payments', label: 'Payments API', utility: 0.82 },
      { id: 'am-ward', label: 'Ward preference v2', utility: 0.61 },
      {
        id: 'am-pytest-old',
        label: 'Older pytest note',
        utility: 0.19,
        excluded: true,
      },
    ],
    schemas: [
      {
        id: 'sch-testing',
        type: 'PREFERENCE',
        summary: 'Testing → Ward v2',
        confidence: 0.85,
      },
      {
        id: 'sch-deploy',
        type: 'PROCEDURE',
        summary: 'Deploy → ECS',
        confidence: 0.92,
      },
      {
        id: 'sch-db',
        type: 'FACT',
        summary: 'DB → DynamoDB',
        confidence: 0.78,
      },
    ],
    budgetUsed: 1720,
  },
  {
    id: 'turn-2',
    chip: 'Standardize all tests on pytest, drop Ward',
    userMessage:
      "We're standardizing every test suite on pytest with fixtures — drop Ward entirely.",
    agentMessage:
      'Migrating the suites to pytest. Ward v2 is now superseded by pytest v3, the lineage remains intact for audit, and the older stray pytest note is archived out of active use.',
    sessionLabel: 'Session 4',
    interferenceNodeIds: ['node-pytest-note'],
    preSnapshotDelay: 2600,
    overlayDuration: 3600,
    replyDelay: 3400,
    dwellAfter: 7000,
    nodes: [
      {
        id: 'node-ward-v1',
        label: 'Ward v1',
        status: 'SUPERSEDED',
        stability: 0.42,
        ...POS.wardV1,
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-ward-v2',
        label: 'Ward v2',
        status: 'SUPERSEDED',
        stability: 0.5,
        ...POS.wardV2,
        parentId: 'node-ward-v1',
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-pytest-v3',
        label: 'pytest v3',
        status: 'ACTIVE',
        stability: 0.68,
        ...POS.pytestV3,
        parentId: 'node-ward-v2',
        isNew: true,
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-fastapi',
        label: 'FastAPI',
        status: 'ACTIVE',
        stability: 0.95,
        ...POS.fastapi,
      },
      {
        id: 'node-pytest-note',
        label: 'pytest note',
        status: 'ARCHIVED',
        stability: 0.12,
        ...POS.pytestNote,
      },
      {
        id: 'node-ecs',
        label: 'ECS + Docker',
        status: 'ACTIVE',
        stability: 0.8,
        ...POS.ecs,
      },
      {
        id: 'node-payments-api',
        label: 'Payments API',
        status: 'ACTIVE',
        stability: 0.58,
        ...POS.paymentsApi,
        parentId: 'node-fastapi',
      },
    ],
    activeMemories: [
      { id: 'am-pytest', label: 'pytest preference v3', utility: 0.94 },
      { id: 'am-fastapi', label: 'FastAPI structure', utility: 0.8 },
      { id: 'am-payments', label: 'Payments API', utility: 0.72 },
      {
        id: 'am-ward',
        label: 'Ward preference v2 (retired)',
        utility: 0.24,
        excluded: true,
      },
    ],
    schemas: [
      {
        id: 'sch-testing',
        type: 'PREFERENCE',
        summary: 'Testing → pytest v3',
        confidence: 0.8,
      },
      {
        id: 'sch-deploy',
        type: 'PROCEDURE',
        summary: 'Deploy → ECS',
        confidence: 0.92,
      },
      {
        id: 'sch-db',
        type: 'FACT',
        summary: 'DB → DynamoDB',
        confidence: 0.78,
      },
    ],
    budgetUsed: 1805,
  },
  {
    id: 'turn-3',
    chip: 'Migrate deploys to the new ECS task def',
    userMessage:
      'Migrate the service to the new containerized ECS task definition and retire the old pipeline.',
    agentMessage:
      'Cut over to the new task definition. ECS + Docker is superseded by Deploy Config v2, and I consolidated your FastAPI + Payments API memories into a reusable "FastAPI Services" schema.',
    sessionLabel: 'Session 4',
    consolidationNodeIds: ['node-fastapi', 'node-payments-api'],
    consolidationLabel: 'FastAPI Services',
    preSnapshotDelay: 1400,
    overlayDuration: 4200,
    replyDelay: 2800,
    dwellAfter: 3200,
    nodes: [
      {
        id: 'node-ward-v1',
        label: 'Ward v1',
        status: 'SUPERSEDED',
        stability: 0.42,
        ...POS.wardV1,
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-ward-v2',
        label: 'Ward v2',
        status: 'SUPERSEDED',
        stability: 0.5,
        ...POS.wardV2,
        parentId: 'node-ward-v1',
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-pytest-v3',
        label: 'pytest v3',
        status: 'ACTIVE',
        stability: 0.66,
        ...POS.pytestV3,
        parentId: 'node-ward-v2',
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-fastapi',
        label: 'FastAPI',
        status: 'CONSOLIDATED',
        stability: 0.96,
        ...POS.fastapi,
      },
      {
        id: 'node-pytest-note',
        label: 'pytest note',
        status: 'ARCHIVED',
        stability: 0.12,
        ...POS.pytestNote,
      },
      {
        id: 'node-payments-api',
        label: 'Payments API',
        status: 'CONSOLIDATED',
        stability: 0.7,
        ...POS.paymentsApi,
        parentId: 'node-fastapi',
      },
      {
        id: 'node-ecs',
        label: 'ECS + Docker',
        status: 'SUPERSEDED',
        stability: 0.7,
        ...POS.ecs,
      },
      {
        id: 'node-deploy-v2',
        label: 'Deploy Config v2',
        status: 'ACTIVE',
        stability: 0.6,
        ...POS.deployV2,
        parentId: 'node-ecs',
        isNew: true,
      },
    ],
    activeMemories: [
      { id: 'am-deploy-v2', label: 'Deploy Config v2', utility: 0.95 },
      { id: 'am-fastapi', label: 'FastAPI structure', utility: 0.84 },
      { id: 'am-payments', label: 'Payments API', utility: 0.79 },
      { id: 'am-pytest', label: 'pytest preference v3', utility: 0.6 },
      {
        id: 'am-ecs',
        label: 'Legacy ECS config (retired)',
        utility: 0.22,
        excluded: true,
      },
    ],
    schemas: [
      {
        id: 'sch-testing',
        type: 'PREFERENCE',
        summary: 'Testing → pytest v3',
        confidence: 0.83,
      },
      {
        id: 'sch-deploy',
        type: 'PROCEDURE',
        summary: 'Deploy → ECS v2',
        confidence: 0.9,
      },
      {
        id: 'sch-stack',
        type: 'FACT',
        summary: 'Stack → FastAPI Services',
        confidence: 0.95,
      },
      {
        id: 'sch-db',
        type: 'FACT',
        summary: 'DB → DynamoDB',
        confidence: 0.78,
      },
    ],
    budgetUsed: 1910,
  },
  {
    id: 'turn-4',
    chip: 'What testing & deploy setup are we on now?',
    userMessage:
      'Just to confirm — what testing and deployment setup are we on right now?',
    agentMessage:
      'You’re on pytest v3 for tests and Deploy Config v2 (containerized ECS) for deploys, against your consolidated FastAPI Services stack. (Read-only — nothing changed in memory.)',
    sessionLabel: 'Session 5',
    divider: {
      label: 'Session 4 ended · Session 5',
      meta: 'Read-only query · no memory mutation',
    },
    preSnapshotDelay: 1400,
    replyDelay: 2500,
    dwellAfter: 3200,
    nodes: [
      {
        id: 'node-ward-v1',
        label: 'Ward v1',
        status: 'SUPERSEDED',
        stability: 0.42,
        ...POS.wardV1,
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-ward-v2',
        label: 'Ward v2',
        status: 'SUPERSEDED',
        stability: 0.5,
        ...POS.wardV2,
        parentId: 'node-ward-v1',
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-pytest-v3',
        label: 'pytest v3',
        status: 'ACTIVE',
        stability: 0.66,
        ...POS.pytestV3,
        parentId: 'node-ward-v2',
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-fastapi',
        label: 'FastAPI',
        status: 'CONSOLIDATED',
        stability: 0.96,
        ...POS.fastapi,
      },
      {
        id: 'node-pytest-note',
        label: 'pytest note',
        status: 'ARCHIVED',
        stability: 0.12,
        ...POS.pytestNote,
      },
      {
        id: 'node-payments-api',
        label: 'Payments API',
        status: 'CONSOLIDATED',
        stability: 0.7,
        ...POS.paymentsApi,
        parentId: 'node-fastapi',
      },
      {
        id: 'node-ecs',
        label: 'ECS + Docker',
        status: 'SUPERSEDED',
        stability: 0.7,
        ...POS.ecs,
      },
      {
        id: 'node-deploy-v2',
        label: 'Deploy Config v2',
        status: 'ACTIVE',
        stability: 0.6,
        ...POS.deployV2,
        parentId: 'node-ecs',
      },
    ],
    activeMemories: [
      { id: 'am-pytest', label: 'pytest preference v3', utility: 0.9 },
      { id: 'am-deploy-v2', label: 'Deploy Config v2', utility: 0.88 },
      { id: 'am-stack', label: 'FastAPI Services', utility: 0.85 },
      { id: 'am-db', label: 'DynamoDB detail', utility: 0.34, excluded: true },
    ],
    schemas: [
      {
        id: 'sch-testing',
        type: 'PREFERENCE',
        summary: 'Testing → pytest v3',
        confidence: 0.83,
      },
      {
        id: 'sch-deploy',
        type: 'PROCEDURE',
        summary: 'Deploy → ECS v2',
        confidence: 0.9,
      },
      {
        id: 'sch-stack',
        type: 'FACT',
        summary: 'Stack → FastAPI Services',
        confidence: 0.95,
      },
      {
        id: 'sch-db',
        type: 'FACT',
        summary: 'DB → DynamoDB',
        confidence: 0.78,
      },
    ],
    budgetUsed: 1480,
  },
  {
    id: 'turn-5',
    chip: 'Show me why we dropped Ward',
    userMessage: 'Show me the audit trail for why Ward was replaced.',
    agentMessage:
      'Opening the lineage trail now. You can see Ward v1, Ward v2, and the active pytest v3 memory, each with the contradiction that pushed the preference forward.',
    sessionLabel: 'Session 5',
    preSnapshotDelay: 900,
    replyDelay: 1800,
    dwellAfter: 7000,
    lineageFocusNodeId: 'node-pytest-v3',
    nodes: [
      {
        id: 'node-ward-v1',
        label: 'Ward v1',
        status: 'SUPERSEDED',
        stability: 0.42,
        ...POS.wardV1,
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-ward-v2',
        label: 'Ward v2',
        status: 'SUPERSEDED',
        stability: 0.5,
        ...POS.wardV2,
        parentId: 'node-ward-v1',
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-pytest-v3',
        label: 'pytest v3',
        status: 'ACTIVE',
        stability: 0.66,
        ...POS.pytestV3,
        parentId: 'node-ward-v2',
        lineage: TESTING_LINEAGE,
      },
      {
        id: 'node-fastapi',
        label: 'FastAPI',
        status: 'CONSOLIDATED',
        stability: 0.96,
        ...POS.fastapi,
      },
      {
        id: 'node-pytest-note',
        label: 'pytest note',
        status: 'ARCHIVED',
        stability: 0.12,
        ...POS.pytestNote,
      },
      {
        id: 'node-payments-api',
        label: 'Payments API',
        status: 'CONSOLIDATED',
        stability: 0.7,
        ...POS.paymentsApi,
        parentId: 'node-fastapi',
      },
      {
        id: 'node-deploy-v2',
        label: 'Deploy Config v2',
        status: 'ACTIVE',
        stability: 0.6,
        ...POS.deployV2,
        parentId: 'node-ecs',
      },
    ],
    activeMemories: [
      { id: 'am-pytest', label: 'pytest preference v3', utility: 0.94 },
      { id: 'am-stack', label: 'FastAPI Services', utility: 0.81 },
      { id: 'am-deploy-v2', label: 'Deploy Config v2', utility: 0.79 },
      {
        id: 'am-ward-legacy',
        label: 'Ward lineage context',
        utility: 0.41,
        excluded: true,
      },
    ],
    schemas: [
      {
        id: 'sch-testing',
        type: 'PREFERENCE',
        summary: 'Testing → pytest v3',
        confidence: 0.83,
      },
      {
        id: 'sch-deploy',
        type: 'PROCEDURE',
        summary: 'Deploy → ECS v2',
        confidence: 0.9,
      },
      {
        id: 'sch-stack',
        type: 'FACT',
        summary: 'Stack → FastAPI Services',
        confidence: 0.95,
      },
      {
        id: 'sch-db',
        type: 'FACT',
        summary: 'DB → DynamoDB',
        confidence: 0.78,
      },
    ],
    budgetUsed: 1525,
  },
];
